GH Action releases

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -27,10 +27,15 @@ jobs:
         uses: actions/checkout@v2
       - name: Check git master branch
         run: |
-          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-          if [[ "$BRANCH" != "master" ]]; then
-            echo "This is not the master branch. Aborting.";
-            exit 1;
+          HEAD="$(cat .git/HEAD)"
+          MASTER="$(cat .git/refs/heads/master)"
+          echo "Head ref is $HEAD"
+          echo "Master ref is $MASTER"
+          if [ "$HEAD" = "$MASTER" ]; then
+              echo "On master branch."
+          else
+              echo "Not on master branch. Aborting."
+              exit 1
           fi
       - name: Set version env
         run: |
